language: rust
os:
  - linux
  - osx
  - windows
rust:
  - nightly
cache: cargo
before_script:
  - cargo install cargo-aoc || echo "cargo-aoc already installed"
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo aoc
